// @ts-check
const eslint = require("@eslint/js");
const { defineConfig } = require("eslint/config");
const tseslint = require("typescript-eslint");
const angular = require("angular-eslint");

module.exports = defineConfig([
  // database.types.ts is generated by `npm run supabase:gen:types` (see
  // CLAUDE.md — "regenerate, don't hand-edit") and its shape comes straight
  // from the Supabase CLI's codegen, not from this codebase's own style
  // conventions, so it's excluded rather than fought with rule overrides.
  {
    ignores: ["src/app/shared/models/database.types.ts"],
  },
  {
    files: ["**/*.ts"],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      "@angular-eslint/directive-selector": [
        "error",
        {
          type: "attribute",
          prefix: "app",
          style: "camelCase",
        },
      ],
      "@angular-eslint/component-selector": [
        "error",
        {
          type: "element",
          prefix: "app",
          style: "kebab-case",
        },
      ],
    },
  },
  // AppComponent is deliberately NgModule-based (standalone: false,
  // constructor injection) — see CLAUDE.md's Architecture section: it's the
  // one root-shell exception to the rest of the app's standalone-component
  // convention, not an oversight these two rules should flag.
  {
    files: ["src/app/app.component.ts"],
    rules: {
      "@angular-eslint/prefer-standalone": "off",
      "@angular-eslint/prefer-inject": "off",
    },
  },
  // Test doubles are expected to have empty/no-op stub methods (that's the
  // point of a fake) and callback params the fake doesn't need — same
  // `_`-prefix convention createFakeSupabaseService et al. already use for
  // "ignore this arg" is honored here rather than fought with real usages.
  {
    files: ["**/*.spec.ts", "src/app/testing/**/*.ts"],
    rules: {
      "@typescript-eslint/no-empty-function": ["error", { allow: ["arrowFunctions"] }],
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    },
  },
  {
    files: ["**/*.html"],
    extends: [
      angular.configs.templateRecommended,
      angular.configs.templateAccessibility,
    ],
    rules: {},
  }
]);
